---
title: "NBA Hackathon Problem 1"
author: "Zeyu Li"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Approach 1: Exact Answer

```{r problem_1_a_exact}
no_closs <- function(win){
  
  ans <- choose((win + 1), (82 - win) ) * 0.8^ win * 0.2^(82 - win)
  
  return(ans)
}
### Probability of no 2 consecutive losses
x <- sum(sapply(41:82, no_closs))

### Probability of consecutive loss
# x <- 1-sum(sapply(41:82, no_closs))

# (c)
# At least game win percentage

least_per <- function(percentage){
  ans <- 0
  for(i in 41 :82){
    ans <- ans + choose((i + 1), (82 - i) ) * percentage^i * 
           (1-percentage)^(82-i)
  }
  ans - 0.5
}

uniroot(least_per,c(0,1))

### At least winning percentage 
# 0.903776165, this is tested by a lot of numbers to get
# different answer from the uniroot function
```
    
The probability that the Warriors would never lose consecutive games at any point during an 82-game season is `r x`.

```{r problem_1_a_simulation, eval = F}
season_simulation <- function(n = 1000){
    
    sample <- 900 # simulate 1000 82-game seasons
    container <- matrix(NA, ncol = sample, nrow = n) # create a container for storing experiment outcomes
    
    for(j in 1:n){
        for(i in 1:sample){
            # set-up
            sample.space <- c(0,1) # win -- 1; loss -- 0
            theta <- 0.8 # Warriors have 80% chance of winning each game
            N <- 82 # 82 games
            # Similar to biased coin flips
            flips <- rbinom(n = N, size = 1, prob = theta)
            # next check for consecutive losses (consecutive 0s)
            r0 <- rle(flips) # list running lengths 
            x <- r0$length[r0$values == 0] # count running length of 0s
            boo <- sum(x != 1) == 0 # consecutive occurrence of 0 or not; 
            # FALSE : there are consecutive loss in a simulated 82-game season
            # TRUE : there are no consecutive loss in a simulated 82-game season
            container[j,i] <- boo
        }
    }
    
    return(container)
}

# (a)
set.seed(123456789) # set starting point
sim <- season_simulation(n = 1000)
y <- rowSums(sim)/ncol(sim) # Prob(no consecutive losses)
mean(y)
hist(y)

# (b)
hist(y)
upp <- mean(y) + 1.96 * sd(y)/sqrt(100)
low <- mean(y) - 1.96 * sd(y)/sqrt(100)
# null hypothesis: Prob(no consecutive losses) = 1
# since null hypothesis is not in the confidence interval, reject null

# (c)
tht <- seq(0, 1, by = 0.001) # check for monotonicity 
tht <- seq(0.89, 0.91, by = 0.0001)
sim <- season_simulation(n = length(tht))
y <- rowSums(sim)/ncol(sim) # probability (no consecutive losses)
ind <- which(abs(y-0.5) == min(abs(y-0.5)))
y[ind]
```



 